# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import socket
from PyQt5 import QtCore, QtGui, QtWidgets
from googletrans import Translator
from FormTools import Ui_FormTools


class Ui_MainForm(object):
    def setupUi(self, MainForm):

        MainForm.setObjectName("MainForm")
        MainForm.resize(930, 422)        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/IMG-TranslateForm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainForm.setWindowIcon(icon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(MainForm.sizePolicy().hasHeightForWidth())
        MainForm.setSizePolicy(sizePolicy)

        #-------- Create Fonts
        fontButtons = QtGui.QFont()
        fontButtons.setFamily("Century Gothic")
        fontButtons.setPointSize(10)

        fontTextEdit = QtGui.QFont()
        fontTextEdit.setFamily("Calibri Light")
        fontTextEdit.setPointSize(14)

        self.gridLayout = QtWidgets.QGridLayout(MainForm)
        self.gridLayout.setObjectName("gridLayout")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.CboSrcLaguage = QtWidgets.QComboBox(MainForm)
        self.CboSrcLaguage.setObjectName("CboSrcLaguage")
        self.horizontalLayout_3.addWidget(self.CboSrcLaguage)

        self.BtnChange = QtWidgets.QPushButton(MainForm)       
        self.BtnChange.setFont(fontButtons)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/IMG-Transfer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnChange.setIcon(icon)
        self.BtnChange.setObjectName("BtnChange")
        self.horizontalLayout_3.addWidget(self.BtnChange)
        self.BtnChange.clicked.connect(self.ChangeLanguage)

        self.CboDestLanguage = QtWidgets.QComboBox(MainForm)
        self.CboDestLanguage.setObjectName("CboDestLanguage")
        self.horizontalLayout_3.addWidget(self.CboDestLanguage)

        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 4)
        self.textSrcLanguage = QtWidgets.QTextEdit(MainForm)
        self.textSrcLanguage.setFont(fontTextEdit)
        self.textSrcLanguage.setStyleSheet("background-color: transparent;")
        self.textSrcLanguage.setObjectName("textSrcLanguage")
        self.textSrcLanguage.textChanged.connect(self.ExecuteTranslate)
       
        self.gridLayout.addWidget(self.textSrcLanguage, 1, 0, 1, 2)
        self.textDestLanguage = QtWidgets.QTextEdit(MainForm)
        self.textDestLanguage.setFont(fontTextEdit)
        self.textDestLanguage.setStyleSheet("background-color: transparent;")
        self.textDestLanguage.setObjectName("textDestLanguage")

        self.gridLayout.addWidget(self.textDestLanguage, 1, 2, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.BtnTools = QtWidgets.QPushButton(MainForm)
        self.BtnTools.setFont(fontButtons)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/IMG-Tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnTools.setIcon(icon1)
        self.BtnTools.setObjectName("BtnTools")
        self.BtnTools.clicked.connect(self.OpenFormTools)

        self.horizontalLayout_2.addWidget(self.BtnTools)
        self.BtnCopy = QtWidgets.QPushButton(MainForm)
        self.BtnCopy.setFont(fontButtons)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/IMG-Copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnCopy.setIcon(icon2)
        self.BtnCopy.setObjectName("BtnCopy")
        self.BtnCopy.clicked.connect(self.CopyText)
        self.horizontalLayout_2.addWidget(self.BtnCopy)

        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 2, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.BtnPaste = QtWidgets.QPushButton(MainForm)
        self.BtnPaste.setFont(fontButtons)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/IMG-Paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnPaste.setIcon(icon3)
        self.BtnPaste.setObjectName("BtnPaste")
        self.horizontalLayout.addWidget(self.BtnPaste)
        self.BtnPaste.clicked.connect(self.PasteText)

        self.BtnClear = QtWidgets.QPushButton(MainForm)
        self.BtnClear.setFont(fontButtons)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/IMG-Clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnClear.setIcon(icon4)
        self.BtnClear.setObjectName("BtnClear")
        self.horizontalLayout.addWidget(self.BtnClear)
        self.BtnClear.clicked.connect(self.ClearText)

        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

        self.InitCombobox()

        self.translator = Translator()

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Language Translate"))
        self.BtnChange.setText(_translate("MainForm", "Change"))
        self.BtnTools.setText(_translate("MainForm", "Tools"))
        self.BtnCopy.setText(_translate("MainForm", "Copy"))
        self.BtnPaste.setText(_translate("MainForm", "Paste"))
        self.BtnClear.setText(_translate("MainForm", "Clear"))

    def InitCombobox(self):
        self.CboSrcLaguage.addItems(["English","Spanish","German","French","Italian","Japanese","Chinese"])
        self.CboDestLanguage.addItems(["English","Spanish","German","French","Italian","Japanese","Chinese"])

    def ExecuteTranslate(self):
        isConnected = self.CheckConnection()

        if(isConnected):
            self.Translate()
        else:
            self.MessageBox("No se pudo establecer la Conexion a Internet","Error")
            return

    def Translate(self):
        try:
            listLanguages = ['en','es','de','fr','it','ja','zh-tw']
            SrcLanguage = self.CboSrcLaguage.currentIndex()
            DestLanguage = self.CboDestLanguage.currentIndex()

            result = self.translator.translate(self.textSrcLanguage.toPlainText(),src=str(listLanguages[SrcLanguage]),
                                    dest=str(listLanguages[DestLanguage]))
            self.textDestLanguage.setPlainText(result.text)
        except:
            if(len(self.textSrcLanguage.toPlainText()) == 1):
                self.textSrcLanguage.clear()
            return
    
    def PasteText(self):
        clipboard = QtGui.QGuiApplication.clipboard()
        mimeData = clipboard.mimeData()

        if mimeData.hasText():
            result = mimeData.text()
            self.textSrcLanguage.setPlainText(result)

    def CopyText(self):
        clipboard = QtGui.QGuiApplication.clipboard()
        clipboard.setText(self.textDestLanguage.toPlainText())

    def ClearText(self):
        self.textSrcLanguage.clear()
        self.textDestLanguage.clear()
    
    def ChangeLanguage(self):
        SrcLanguage = self.CboSrcLaguage.currentIndex()
        DestLanguage = self.CboDestLanguage.currentIndex()

        self.CboSrcLaguage.setCurrentIndex(DestLanguage)
        self.CboDestLanguage.setCurrentIndex(SrcLanguage)

        textLastlanguage = self.textDestLanguage.toPlainText()
        self.textSrcLanguage.setPlainText(textLastlanguage)
    
    def OpenFormTools(self):        
        self.window = QtWidgets.QWidget()
        
        self.ui = Ui_FormTools(self.textDestLanguage.toPlainText())
        self.ui.setupUi(self.window)
        self.window.show()

    def CheckConnection(self):
        REMOTE_SERVER = "www.google.com"
        try:
            host = socket.gethostbyname(REMOTE_SERVER)
            connect = socket.create_connection((host,80),2)
            return True
        except:
            return False
    
    def MessageBox(self,message,title):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText(message)
        msg.setWindowTitle(title)
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msg.exec()
        return


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)

    MainForm = QtWidgets.QWidget()

    ui = Ui_MainForm()

    ui.setupUi(MainForm)

    p = QtGui.QPalette()
    gradient = QtGui.QLinearGradient(0, 0, 0, 400)
    gradient.setColorAt(0.0, QtGui.QColor(251, 252, 252))
    gradient.setColorAt(1.0, QtGui.QColor(208, 211, 212))
    p.setBrush(QtGui.QPalette.Window, QtGui.QBrush(gradient))
    MainForm.setPalette(p)

    MainForm.show()

    sys.exit(app.exec_())
